# Site
repository: "anjihub/anjelipancholi.github.io"

# Content configuration version
version: 2

# Personal info
name: "Anjeli Pancholi"
title: "Aspiring Cybersecurity Professional"
email: "apancholi2002@gmail.com"
phone: "9804351177"

# Dark Mode (true/false/never) - enable toggle
darkmode: true

# Social links
github_username: "anjihub"
stackoverflow_username: "31226648"
linkedin_username: "anjeli-pancholi"

# About Section
about_content: |
  I am Anjeli Pancholi, a dedicated computer science student specializing in cybersecurity and digital forensics.  
  My passion for technology began at an early age and has driven me to pursue a career focused on protecting digital assets and supporting law enforcement efforts.  
  I aim to leverage my technical expertise to contribute to cybersecurity initiatives, with a strong commitment to ethical practices and public safety.  
  I am particularly interested in forensic analysis, ethical hacking, and developing innovative tools to safeguard information and infrastructure.

content:
  - title: "Resume"
    layout: "list"
    content:
      - layout: "left"
        title: "Download My Resume"
        description: |
          You can download my resume here:  
          [Resume PDF](https://anjihub.github.io/anjelipancholi.github.io/Resume_Anjeli_Pancholi.pdf)

  - title: "Blog"
    layout: "list"
    content:
      - layout: "left"
        title: "Visit My Blog"
        description: |
          Welcome to my cybersecurity blog where I share projects, certifications, and insights.  
          Whether you're a fellow student, a recruiter, or just curious about cybersecurity, I hope you find something valuable here:  
          [My Blog](https://anjeli.hashnode.dev/)

  - title: "Projects"
    layout: "list"
    content:
      - layout: "left"
        border: "weak"
        title: "Project name"
        link: "Link to project (eg. sproogen.github.io/modern-resume-theme)"
        link_text: "Link Text"
        additional_links:
          - title: "Github page for project"
            icon: "fab fa-github"
            url: "https://github.com/anjihub"
        quote: >
          Short overview of the project (optional)
        description: |
          Description about the work on/with the project

  - title: "Experience"
    layout: "list"
    content:
      - layout: "left"
        title: "Company name"
        sub_title: "Job title"
        caption: "Date Range (eg. November 2016 - present)"
        quote: >
          Short description of the company (optional)
        description: |
          Description of role

  - title: "Education"
    layout: "list"
    content:
      - layout: "left"
        title: "Wake Technical Community College"
        sub_title: "Associates in Information Technology: Cybersecurity"
        caption: "2024-2026"
        description: |
          Pursuing a comprehensive curriculum focused on cybersecurity principles, network security, ethical hacking, and digital forensics. Gaining hands-on experience with security tools and techniques to protect information systems and respond to cyber threats.

      - layout: "left"
        title: "Central Piedmont Community College"
        sub_title: "General Courses & Nurse Aid I Certification"
        caption: "2021-2023"
        description: |
          Completed foundational coursework to support further technical education and professional development. Earned Nurse Aid I Certification, demonstrating commitment to disciplined study and care-oriented skills alongside technical interests.

  - title: "Certifications"
    layout: "list"
    content:
      - layout: "left"
        title: "Cisco CCNA: Switching, Routing, and Wireless Essentials"
        caption: "Issued May 2025"
        description: "Mastered foundational networking concepts including switching, routing, and wireless technologies essential for building and managing enterprise networks."

      - layout: "left"
        title: "IT Specialist - Python (Certiport)"
        caption: "Issued May 2025"
        description: "Demonstrated proficiency in Python programming for automation, scripting, and problem-solving within IT environments."

      - layout: "left"
        title: "Cisco CCNA: Introduction to Networks"
        caption: "Issued March 2025"
        description: "Gained fundamental knowledge of networking principles, protocols, and architectures, laying the groundwork for advanced networking skills."

      - layout: "left"
        title: "LinkedIn Learning Certificates"
        description: |
          - Change Management Foundations  
          - DevOps Foundations  
          - Diversity, Equity, Inclusion, and Belonging (DEIB)  
          - IT Service Management Foundations: Problem Management  
          - Agile Foundations  
          - Conflict Management  
          - Git Essential Training  
          - Learning Computer Security and Internet Safety  
          - Learning Git and GitHub  

  - title: "Skills & Technologies"
    layout: "list"
    content:
      - layout: "left"
        title: "Skills Summary"
        description: |
          - Python  
          - Git  
          - Cisco  
          - JavaScript  
          - HTML  

# Footer
footer_show_references: true

# Build settings
remote_theme: "sproogen/modern-resume-theme"

sass:
  sass_dir: "_sass"
  style: "compressed"

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"

# Custom CSS for resume button and left align certs + education
custom_css: |
  .btn {
    background-color: #007ACC;
    color: white !important;
    padding: 10px 18px;
    border-radius: 6px;
    text-decoration: none;
    font-weight: 600;
  }
  .btn:hover {
    background-color: #005A99;
  }

  /* Left align Education and Certifications */
  section.education, section.certifications {
    text-align: left !important;
  }
  section.education .content,
  section.certifications .content {
    text-align: left !important;
  }

  /* Show descriptions properly under certifications */
  section.certifications .content > div > p {
    margin-top: 0.4em;
    margin-bottom: 1em;
    font-size: 0.95em;
    color: #444;
  }

  /* Show descriptions properly under education */
  section.education .content > div > p {
    margin-top: 0.4em;
    margin-bottom: 1em;
    font-size: 0.95em;
    color: #444;
    white-space: pre-wrap; /* preserves line breaks */
  }
