# Site
repository: "anjihub/anjelipancholi.github.io"

# Content configuration version
version: 2

# Personal info
name: "Anjeli Pancholi"
title: "Aspiring Cybersecurity Professional"
email: "apancholi2002@gmail.com"
phone: "9804351177"

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: "anjihub"
stackoverflow_username: "31226648"
linkedin_username: "anjeli-pancholi"

# About Section
about_content: |
  I’m Anjeli Pancholi — a passionate and detail-oriented cybersecurity student focused on digital forensics and cybercrime investigation.  
  With a strong foundation in IT and a drive to support law enforcement and ethical cybersecurity practices,  
  I aim to contribute to protecting data, networks, and people in the digital world.  
  I'm particularly interested in forensic analysis, ethical hacking, and the intersection of cybersecurity with justice and safety.  

  ![Cybersecurity Image](https://focus.namirial.global/wp-content/uploads/sites/4/2023/06/ai-in-cybersecurity.jpeg){: style="width:100%; max-width:600px; margin-top: 20px; margin-bottom: 40px;" }

content:
  - title: "Resume"
    layout: "list"
    content:
      - layout: "left"
        title: "Download My Resume"
        description: |
          You can download my resume here:  
          [Resume PDF](https://anjihub.github.io/anjelipancholi.github.io/Resume_Anjeli_Pancholi.pdf)

  - title: "Blog"
    layout: "list"
    content:
      - layout: "left"
        title: "Visit My Blog"
        description: |
          I regularly share insights and updates about cybersecurity, tech trends, and career development.  
          Check out my blog here:  
          [My Blog](https://yourblogurl.com)  

  - title: "Projects"
    layout: "list"
    content:
      - layout: "left"
        border: "weak"
        title: "Project name"
        link: "Link to project (e.g., https://sproogen.github.io/modern-resume-theme)"
        link_text: "Link Text"
        additional_links:
          - title: "GitHub page for project"
            icon: "fab fa-github"
            url: "https://github.com/anjihub"
        quote: >
          Short overview of the project (optional)
        description: |
          Description about the work on/with the project

  - title: "Experience"
    layout: "list"
    content:
      - layout: "left"
        title: "Company name"
        sub_title: "Job title"
        caption: "Date Range (e.g., November 2016 - Present)"
        quote: >
          Short description of the company (optional)
        description: |
          Description of role

  - title: "Education"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Wake Technical Community College"
        sub_title: "Associates in Information Technology: Cybersecurity"
        caption: "2024–2026"
      - layout: "top-right"
        title: "Central Piedmont Community College"
        sub_title: "General Courses & Nurse Aid I Certification"
        caption: "2021–2023"

  - title: "Certifications"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Cisco CCNA: Switching, Routing, and Wireless Essentials"
        caption: "Issued May 2025"
      - layout: "top-right"
        title: "IT Specialist - Python (Certiport)"
        caption: "Issued May 2025"
      - layout: "top-right"
        title: "Cisco CCNA: Introduction to Networks"
        caption: "Issued March 2025"
      - layout: "top-right"
        title: "LinkedIn Learning Certificates"
        description: |
          - Change Management Foundations  
          - DevOps Foundations  
          - Diversity, Equity, Inclusion, and Belonging (DEIB)  
          - IT Service Management Foundations: Problem Management  
          - Agile Foundations  
          - Conflict Management  
          - Git Essential Training  
          - Learning Computer Security and Internet Safety  
          - Learning Git and GitHub  

  - title: "Skills & Technologies"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Skills Summary"
        description: |
          - Python  
          - Git  
          - Cisco  
          - JavaScript  
          - HTML  

# Footer
footer_show_references: true

# Build settings
remote_theme: "sproogen/modern-resume-theme"

sass:
  sass_dir: "_sass"
  style: "compressed"

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"

# Custom CSS for Resume Button
custom_css: |
  .btn {
    background-color: #007ACC;
    color: white !important;
    padding: 10px 18px;
    border-radius: 6px;
    text-decoration: none;
    font-weight: 600;
  }
  .btn:hover {
    background-color: #005A99;
  }
