# Site
repository: "anjihub/anjelipancholi.github.io"

# Content configuration version
version: 2

# Personal info
name: "Anjeli Pancholi"
title: "Aspiring Cybersecurity Professional"
email: "apancholi2002@gmail.com"
phone: "9804351177"

# Dark Mode (true/false/never) - enable toggle
darkmode: true

# Social links
github_username: "anjihub"
stackoverflow_username: "31226648"
linkedin_username: "Anjeli Pancholi"

# About Section
about_content: |
  I am Anjeli Pancholi, a dedicated computer science student specializing in cybersecurity and digital forensics.  
  My passion for technology began at an early age and has driven me to pursue a career focused on protecting digital assets and supporting law enforcement efforts.  
  I aim to leverage my technical expertise to contribute to cybersecurity initiatives, with a strong commitment to ethical practices and public safety.  
  I am particularly interested in forensic analysis, ethical hacking, and developing innovative tools to safeguard information and infrastructure.

content:
  - title: "Resume"
    layout: "list"
    content:
      - layout: "left"
        title: "Download My Resume"
        description: |
          You can download my updated resume here:  
          [Resume PDF](https://github.com/anjihub/anjelipancholi.github.io/raw/master/Updated%20Resume%20-%20Anjeli%20Pancholi.pdf)

  - title: "Blog"
    layout: "list"
    content:
      - layout: "left"
        title: "Visit My Blog"
        description: |
          Welcome to my cybersecurity blog where I share projects, certifications, and insights.  
          Whether you're a fellow student, a recruiter, or just curious about cybersecurity, I hope you find something valuable here:  
          [My Blog](https://anjeli.hashnode.dev/)

  - title: "Projects"
    layout: "list"
    content:
      - layout: "left"
        border: "weak"
        title: "Learning to utilize Mermaid Diagrams"
        link: "https://github.com/anjihub/mermaid-diagram"
        link_text: "View Project on GitHub"
        additional_links:
          - title: "Github page for project"
            icon: "fab fa-github"
            url: "https://github.com/anjihub"
        quote: >
          Visualizing network security attack flows with Mermaid diagrams to simplify complex concepts.
        description: |
          This project uses Mermaid, a markdown-friendly diagram tool, to create clear and concise sequence diagrams illustrating a botnet attack scenario.
          It helped me practice representing cybersecurity processes visually and enhanced my understanding of attack-defense interactions.

  - title: "Experience"
    layout: "list"
    content:
      - layout: "left"
        title: "SOC Analyst Intern (Paid)"
        sub_title: "Carolina Cyber Network – Montreat College Campus"
        caption: "Sept 2025 – Present"
        description: |
          Participating in a structured, paid training program designed to build work-ready SOC analyst skills.  
          Gaining hands-on exposure to commercial and open-source security tools for scanning, scripting, and penetration testing.  
          Applying cybersecurity concepts daily, including log analysis, event monitoring, and vulnerability assessment.  
          Shadowing experienced analysts to understand alert triage, escalation, and incident response workflows.  
          Developing practical skills for entry-level roles in SOC operations and cyber defense.

  - title: "Education"
    layout: "list"
    content:
      - layout: "left"
        title: "Wake Technical Community College"
        sub_title: "AAS, Cybersecurity"
        caption: "Expected May 2026 | GPA: 4.0"
        description: |
          ● President’s List (Fall & Spring 2024)  
          ● Golden Leaf & NC Next Scholarships

  - title: "Certifications"
    layout: "list"
    content:
      - layout: "left"
        title: "Cisco CCNA: Introduction to Networks"
        caption: "Issued Mar 2025"
