# Site
repository: "anjihub/anjelipancholi.github.io"

# Content configuration version
version: 2

# Personal info
name: "Anjeli Pancholi"
title: "Aspiring Cybersecurity Professional"
email: "apancholi2002@gmail.com"
phone: "(980) 435-1177"

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: "anjihub"
stackoverflow_username: "31226648"
linkedin_username: "Anjeli Pancholi"

# About Section
about_profile_image: "images/profile.jpg"
about_content: |
  My name is Anjeli Pancholi, and I've been passionate about computers since I was seven years old, when I first started playing video games with my brother.
  That early fascination sparked a lifelong interest in technology and set me on a path toward a career in computing.
  I'm currently studying computer science with a focus on cybersecurity and digital forensics. My goal is to work in cybersecurity within law enforcement,
  where I can combine my passion for justice and protecting others with my technical skills. I’m especially interested in using technology to support the greater good,
  whether through forensic investigation, ethical hacking, or building tools that help keep people safe.

  ![Cybersecurity Image](https://focus.namirial.global/wp-content/uploads/sites/4/2023/06/ai-in-cybersecurity.jpeg)

content:
  - title: "Projects"
    layout: "list"
    content:
      - layout: "left"
        border: "weak"
        title: "Project name"
        link: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
        link_text: "Link Text"
        additional_links:
          - title: "Github page for project (eg. sproogen/modern-resume-theme)"
            icon: "fab fa-github"
            url: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
          - title: "Github page for project (eg. sproogen/modern-resume-theme)"
            icon: "fab fa-github"
            url: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
        quote: >
          Short overview of the project (optional)
        description: |
          Description about the work on/with the project

  - title: "Experience"
    layout: "list"
    content:
      - layout: "right"
        title: "Company name"
        sub_title: "Job title"
        caption: "Date Range (eg. November 2016 - present)"
        quote: >
          Short description of the company (optional)
        description: |
          Description of role

  - title: "Education"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Wake Technical Community College"
        sub_title: "Associates in Information Technology: Cybersecurity"
        caption: "2024-2026"
      - layout: "top-right"
        title: "Central Piedmont Community College"
        sub_title: "General Courses & Nurse Aid I Certification"
        caption: "2021-2023"

  - title: "Certifications & Skills"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Cisco CCNA: Switching, Routing, and Wireless Essentials"
        caption: "Issued May 2025"
      - layout: "top-right"
        title: "IT Specialist - Python (Certiport)"
        caption: "Issued May
