# Site
repository: "Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)"
# favicon: "Directory of your favicon (eg. images/favicon.ico)(optional)"

# Content configuration version
version: 2

# Personal info
name: "Anjeli Pancholi"
title: "Aspiring Cybersecurity Professional"
email: "apancholi2002@gmail.com"
# email_title: Email (Email title override)
phone: "(980) 435-1177"
# phone_title: Phone (Phone title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: "anjihub"
stackoverflow_username: "00000001"
linkedin_username: anjeli-pancholi-11280b272

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: "Directory of profile image (eg. images/profile.jpg)"
about_content: | # this will include new lines to allow paragraphs
  My name is Anjeli Pancholi, and I've been passionate about computers since I was seven years old, when I first started playing video games with my brother.
  That early fascination sparked a lifelong interest in technology and set me on a path toward a career in computing.
  I'm currently studying computer science with a focus on cybersecurity and digital forensics. My goal is to work in cybersecurity within law enforcement,
  where I can combine my passion for justice and protecting others with my technical skills. I’m especially interested in using technology to support the greater good,
  whether through forensic investigation, ethical hacking, or building tools that help keep people safe.

  ![Cybersecurity Image](https://focus.namirial.global/wp-content/uploads/sites/4/2023/06/ai-in-cybersecurity.jpeg)

content:
  - title: "Projects"
    layout: "list"
    content:
      - layout: "left"
        border: "weak"
        title: "Project name"
        link: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
        link_text: "Link Text"
        additional_links:
          - title: "Github page for project (eg. sproogen/modern-resume-theme)"
            icon: "fab fa-github"
            url: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
          - title: "Github page for project (eg. sproogen/modern-resume-theme)"
            icon: "fab fa-github"
            url: "Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)"
        quote: >
          Short overview of the project (optional)
        description: |
          Description about the work on/with the project
  - title: "Experience"
    layout: "list"
    content:
      - layout: "right"
        title: "Company name"
        sub_title: "Job title"
        caption: "Date Range (eg. November 2016 - present)"
        quote: >
          Short description of the company (optional)
        description: |
          Description of role
  - title: "Education"
    layout: "list"
    content:
      - layout: "top-right"
        title: "Wake Technical Community College"
        sub_title: "Associates in Information Technology: Cybersecurity"
        caption: "2024-2026"


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: "sproogen/modern-resume-theme"

navigation:
  - title: "Resume"
    url: "/Anjeli_Pancholi_Resume.pdf"

sass:
  sass_dir: "_sass"
  style: "compressed"

plugins:
  - jekyll-seo-tag

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "lib/"
  - "scripts/"
  - "docker-compose.yml"
